server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # C'est cette ligne qui fait la magie pour le vue-router :
    location / {
        try_files $uri $uri/ /index.html;
    }
}